name: tests

on:
  push:
    branches:
      - develop
      - main
      - 'feature/**'
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: image_identifier_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Install Dependencies
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Build Assets
        run: npm run build

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Set Filesystem Disk for Tests
        run: echo "FILESYSTEM_DISK=public" >> .env

      - name: Set Database Configuration
        run: |
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=image_identifier_test" >> .env
          echo "DB_USERNAME=postgres" >> .env
          echo "DB_PASSWORD=postgres" >> .env

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Set API Keys and Spark Plan IDs
        run: |
          echo "STRIPE_KEY=${{ secrets.STRIPE_KEY }}" >> .env
          echo "STRIPE_SECRET=${{ secrets.STRIPE_SECRET }}" >> .env
          echo "SPARK_STANDARD_MONTHLY_PLAN=${{ secrets.SPARK_STANDARD_MONTHLY_PLAN }}" >> .env
          echo "SPARK_STANDARD_YEARLY_PLAN=${{ secrets.SPARK_STANDARD_YEARLY_PLAN }}" >> .env
          echo "SPARK_STARTUP_MONTHLY_PLAN=${{ secrets.SPARK_STARTUP_MONTHLY_PLAN }}" >> .env
          echo "SPARK_STARTUP_YEARLY_PLAN=${{ secrets.SPARK_STARTUP_YEARLY_PLAN }}" >> .env
          echo "SPARK_ENTERPRISE_MONTHLY_PLAN=${{ secrets.SPARK_ENTERPRISE_MONTHLY_PLAN }}" >> .env
          echo "SPARK_ENTERPRISE_YEARLY_PLAN=${{ secrets.SPARK_ENTERPRISE_YEARLY_PLAN }}" >> .env
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
          echo "COHERE_API_KEY=${{ secrets.COHERE_API_KEY }}" >> .env

      - name: Tests
        run: ./vendor/bin/pest --exclude-group=stripe
